services:
  web:
    build: .
    container_name: bitrix_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./bitrix:/var/www/html/bitrix
      - ./upload:/var/www/html/upload
      - ./logs/apache:/var/log/apache2
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: bitrix_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=bitrix
      - MYSQL_USER=bitrix
      - MYSQL_PASSWORD=bitrix_password
    ports:
      - "3306:3306"


volumes:
  db_data:
